/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define LED_PIN_ON_STATE 1
#define LED_CAPS_LOCK_PIN GP0
#define LED_NUM_LOCK_PIN GP22
